config/routes.rb
WaveVisionMarketing::Application.routes.draw do
 
  root to: 'static_pages#home'

  match '/aboutus',   to: 'static_pages#aboutus'
  match '/services',  to: 'static_pages#services'
  match '/careers',   to: 'static_pages#careers'
  match '/new_applicant',    to: 'static_pages#new_applicant'
  match '/questions',    to: 'static_pages#questions'

  match '/contact' => 'contact#new', :as => 'contact', :via => :get
  match '/contact' => 'contact#create', :as => 'contact', :via => :post

  match '/apply' => 'apply#new', :as => 'apply', :via => :get
  match '/apply' => 'apply#create', :as => 'apply', :via => :post

end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name, :address, :address2, :city, :st, :zip
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :phone_number, :subject, :body, :additional_information, :type

  validates :name, :email, :phone_number, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/apply_controller.rb
class ApplyController < ApplicationController
	def new
    	@message = Message.new
    	@company = Company.find_by_name("Wave Vision Marketing")
  	end

  	def create
    	@message = Message.new(params[:message])
    	@company = Company.find_by_name("Wave Vision Marketing")
    
    	if @message.valid?
      		NotificationsMailer.new_resume(@message).deliver
      		redirect_to(apply_path, :notice => "Message was successfully sent.")
    	else
      		flash.now.alert = "Please fill out all fields."
      		render :new
    	end
  	end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @message = Message.new
    @company = Company.find_by_name("Wave Vision Marketing")
  end

  def create
    @message = Message.new(params[:message])
    @company = Company.find_by_name("Wave Vision Marketing")

    if @message.valid?
      NotificationsMailer.new_question(@message).deliver
      redirect_to(contact_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill out all fields."
      render :new
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @company = Company.find_by_name("Wave Vision Marketing")

  end

  def aboutus
    @company = Company.find_by_name("Wave Vision Marketing")

  end

  def services
    @company = Company.find_by_name("Wave Vision Marketing")
  end

  def careers
    @company = Company.find_by_name("Wave Vision Marketing")
  end

  def apply
    @company = Company.find_by_name("Wave Vision Marketing")
  end

  def contact
    @company = Company.find_by_name("Wave Vision Marketing")
  end

  # ------- METHODS -------------


  def new_applicant

  end

  def questions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "Wave Vision Marketing"

		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/apply_helper.rb
module ApplyHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/supports_helper.rb
module SupportsHelper
end

app/views/apply/new.html.erb
<% provide(:title, 'Apply') %>
<!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag "city.jpg" %>
          <div class="container">
            <div class="carousel-caption">
              <h1>Apply Online with <%= @company.name %></h1>
              <p class="lead">“Coming together is a beginning; keeping together is progress; working together is success.” ― Henry Ford</p>
            </div>
          </div>
        </div>

      </div>
     
    </div><!-- /.carousel -->




      <!-- START THE FEATURETTES -->
      
      <% flash.each do |name, msg| %>
         <% if msg.is_a?(String) %>
         <div class="alert alert-dismissable alert-danger">
            <%= content_tag :div, msg, :class => "flash_#{name}" %>
          </div>
        <% end %>
        <% end %>
        

      <hr class="featurette-divider">



      <div class="featurette">
        <p class="lead">Very seldom do we find the opportunity that allows us to climb the ladder of success by working hard and being rewarded accordingly for it. This is that OPPORTUNITY! Don’t miss the chance to achieve your goals and aspirations for the future. We will review all applications submitted, no matter the experience level you have. Are you ready? Are you driven? determined? Excited about attaining goals? How fast will you climb the ladder? Fill out the form below to apply with us now.</p>

        </div>

        

        <%= form_for @message, :class => "form-horizontal", :url => apply_path do |form| %>
          <fieldset class="form-group">
          <div class="field">

            <%= form.label :name, :class => "col-lg-2 control-label" %>
            <%= form.text_field :name%>
          </div>
    
          <div class="form-group">
            <%= form.label :email, :class => "col-lg-2 control-label" %>
            <%= form.text_field :email %>
          </div>
          
          <div class="form-group">
            <%= form.label :phone_number, :class => "col-lg-2 control-label"  %>
            <%= form.text_field :phone_number %>
          </div>
    
          <div class="form-group">
            <%= form.label "Resume:", :class => "col-lg-2 control-label"  %>
            <%= form.text_area :body %>
          </div>

          <div class="form-group">
              <%= form.label "How did you hear about us?", :class => "col-lg-2 control-label"  %>
              <%= form.text_field :additional_information %>
          </div>
  </fieldset>
  
  <fieldset class="actions">
    <%= form.submit "Send", :class => "btn btn-large btn-primary btn_resize" %>
  </fieldset>
<% end %>

<%= render "static_pages/digitalPresence" %>

<%= render "static_pages/footer" %>

app/views/contact/new.html.erb
<% provide(:title, 'Contact') %>

<!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag "city.jpg" %>
          <div class="container">
            <div class="carousel-caption">
              <h1>Contact <%= @company.name %></h1>
              <p class="lead">“Those who do not learn from history are doomed to repeat it.” –George Santayana</p>
            </div>
          </div>
        </div>

      </div>
     
    </div><!-- /.carousel -->




      <!-- START THE FEATURETTES -->
      
      <% flash.each do |name, msg| %>
         <% if msg.is_a?(String) %>
         <div class="alert alert-dismissable alert-danger">
        <%= content_tag :div, msg, :class => "flash_#{name}" %>
        </div>
        <% end %>
        <% end %>
        

      <hr class="featurette-divider">

      <div class="featurette">
        <p class="lead">Please use the form below to contact us by email:</p>


<%= form_for @message, :type => "contact", :url => contact_path do |form| %>
  <fieldset class="form-group">
    <div class="field">
      <%= form.label :name, :class => "col-lg-2 control-label" %>
      <%= form.text_field :name %>
    </div>
    
    <div class="field">
      <%= form.label :email, :class => "col-lg-2 control-label" %>
      <%= form.text_field :email %>
    </div>
    <div class="field">
      <%= form.label :phone_number, :class => "col-lg-2 control-label" %>
      <%= form.text_field :phone_number %>
    </div>
    
    <div class="field">
      <%= form.label "Message or Question", :class => "col-lg-2 control-label" %>
      <%= form.text_area :body %>
    </div>
  </fieldset>
  
  <fieldset class="actions">
    <%= form.submit "Send", :class => "btn btn-large btn-primary btn_resize" %>
  </fieldset>
<% end %>

<%= render "static_pages/digitalPresence" %>


<%= render "static_pages/footer" %>

app/views/layouts/_header.html.erb
<header class ="navbar navbar-fixed-top">


<div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
   <%= link_to "wave vision marketing", root_path, id: "logo", :class => "navbar-brand" %>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to "Home",			root_path %></li>
      <li><%= link_to "About Us",		aboutus_path %></li>
	  <li><%= link_to "Services",		services_path %></li>
	  <li><%= link_to "Careers",		careers_path %></li>
	  <li><%= link_to "Apply Online",	apply_path %></li>
	  <li><%= link_to "Contact",		contact_path %></li>
    </ul>
		
	</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9] >
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif] -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag "bootstrap.css" %>
  <%= csrf_meta_tags %>


     <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>

	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/static_pages/_contactform.html.erb
<% form_for @support, :url => { :action => "create" }, :html => { :method => :post } do |f| %>
  <p>
    <%= f.label "Name" %>
  </p>
  <p>
    <%= f.text_field :sender_name %>
  </p>
  <p>
    <%= f.label "Email" %>
  </p>
  <p>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label "Phone  Number" %>
  </p>
  <p>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label "Message or Question:" %>
  </p>
  <p>
    <%= f.text_area :question %>
  </p>
  <p>
    <%= f.submit "Submit", :class => "btn btn-large btn-primary btn_custom" %>
  </p>
<% end %>

app/views/static_pages/_digitalPresence.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script><!-- gmaps scripts end-->

<script>

// $( document ).ready(function() {
//   handler = Gmaps.build('Google');
// 	handler.buildMap({ internal: {id: 'map'}}, function(){
//   	markers = handler.addMarkers([
//     {
//       lat: 35.208793,
//       lng: -111.614477,
//       picture: {
//         url: "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
//         width:  36,
//         height: 36
//       },
//       infowindow: "hello!"
//     }
//   ]);
// });
// });
// });

	

</script>

<hr class="featurette-divider">
<p class="lead">
	<%= @company.name %>
	<br />
	<%= @company.address %>
	<br />
	<%= @company.city %>, <%=@company.st%> <%=@company.zip.to_s %>
	 
	 <div><!-- google map-->
  		<!-- <div id="map" style='width: 100%; height: 300px;'></div> -->
	</div>
</p>




<!-- google map end-->

<script type="text/javascript">
// handler = Gmaps.build('Google');
// handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
//   markers = handler.addMarkers([
//     {
//       lat: 35.208793,
//       lng: -111.614477,
//       "infowindow": "Wave-Vision Marketing - 2028 N. Third Street Flagstaff, AZ"
//     }
//   ]);
//   handler.bounds.extendWith(markers);
//   handler.fitMapToBounds();
// });


</script>

app/views/static_pages/_footer.html.erb
 <!-- FOOTER -->
 <br /> <br />
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2014 <%= @company.name %>, Inc.</p>
      </footer>

    </div><!-- /.container -->



    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../assets/js/jquery.js"></script>
    <script src="../assets/js/bootstrap-transition.js"></script>
    <script src="../assets/js/bootstrap-alert.js"></script>
    <script src="../assets/js/bootstrap-modal.js"></script>
    <script src="../assets/js/bootstrap-dropdown.js"></script>
    <script src="../assets/js/bootstrap-scrollspy.js"></script>
    <script src="../assets/js/bootstrap-tab.js"></script>
    <script src="../assets/js/bootstrap-tooltip.js"></script>
    <script src="../assets/js/bootstrap-popover.js"></script>
    <script src="../assets/js/bootstrap-button.js"></script>
    <script src="../assets/js/bootstrap-collapse.js"></script>
    <script src="../assets/js/bootstrap-carousel.js"></script>
    <script src="../assets/js/bootstrap-typeahead.js"></script>
    <script>
      !function ($) {
        $(function(){
          // carousel demo
          $('#myCarousel').carousel()
        })
      }(window.jQuery)
    </script>
    <script src="../assets/js/holder/holder.js"></script>

app/views/static_pages/aboutus.html.erb
<% provide(:title, 'About Us') %>


<!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag "city.jpg" %>
          <div class="container">
            <div class="carousel-caption">
              <h1>About <%= @company.name %></h1>
              <p class="lead">“The way to get started is to quit talking and begin doing. ” ― Walt Disney Company</p>

              <%= link_to "Apply Today!",	apply_path, :class => "btn btn-large btn-primary"  %>

            </div>
          </div>
        </div>

      </div>
     
    </div><!-- /.carousel -->



    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="span3">
          <%=image_tag "whatWeDo.jpg", :class => "img-circle" %>
          <h2>What We Do</h2>
          <p><%= @company.name %> is a marketing firm that specializes in marketing programs for our clients’ products and services. The client base for <%= @company.name %> has expanded to leaders in Satellite Television and Consumer Electronics. With the unveiling of our solidified and effective marketing program in the prestigious city of <%= @company.city %>, <%= @company.st %>, <%= @company.name %> has developed an undeniably powerful presence in some of the world’s largest chain retailers in a short amount time.</p>
        </div><!-- /.span4 -->
        <div class="span3">
          <%=image_tag "values.jpg", :class => "img-circle" %>
          <h2><%= @company.name %> Values</h2>
          <p>Fundamental values have been solidified into our business culture through various different backgrounds and experience from the founders of our business.  These experiences come from several distinctive backgrounds of Sports Management, Military Background, Coaching, Personal Training, Business Management, Entrepreneurs, Accountants, Financial Advisers, and several other respective fields which we are proud to say make up the potent values of our company. These values have been implemented and structured into a Business/Management Development Program that has built and shaped our company to the prestigious and opportunistic company that it is today.</p>
        </div><!-- /.span4 -->
        <div class="span3">
          <%=image_tag "future.jpg", :class => "img-circle" %>
          <h2>The Future</h2>
          <p>By taking advantage of <%= @company.name %> Business/Management training and opportunities for professional development, even those with limited work experience can build personal and professional skills that will last a lifetime. The future is bright and consistent at <%= @company.name %> for individuals who are team players, creative thinkers and self starters who are goal and detail-oriented and have an affinity for working with people. Most openings require no experience and are considered entry level.</p>
        </div><!-- /.span4 -->
      </div><!-- /.row -->


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="featurette">
        
        <h2 class="featurette-heading">The Industry Scope of our Clients… </h2>
        <h3><span class="muted">The Client’s Role</span></h3>
        <p class="lead">Our Success is attributed to our clients. Our strong client base allows us to create a substantial opportunity for individuals willing to work hard to reach their goals.</p>
        <%= link_to "Click here to learn more", services_path %>
      </div>



      <!-- /END THE FEATURETTES -->


      <%= render "digitalPresence" %>

     <%= render "footer" %>

app/views/static_pages/careers.html.erb
<% provide(:title, 'Careers') %>



<!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag "city.jpg" %>
          <div class="container">
            <div class="carousel-caption">
              <h1>Career Opportunities with <%= @company.name %></h1>
              <p class="lead">“Success consists of going from failure to failure without loss of enthusiasm. ” ― Winston Churchill</p>
              <%= link_to "Apply Today", apply_path,  class: "btn btn-large btn-primary" %>
            </div>
          </div>
        </div>

      </div>
     
    </div><!-- /.carousel -->



    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="span3">
        	<%= image_tag "client.jpg", :class => "img-circle" %>
          
          <h2>The Client</h2>
          <p><%= @company.name%> is a <%= @company.city %>-based marketing firm that specializes at In-Store Marketing programs for our clients’ products and services. <%= @company.name%> was created to acquire and retain customers in a personalized manner for all types of companies.</p>
        </div><!-- /.span3 -->
        <div class="span3">
          <%= image_tag "experience.jpg", :class => "img-circle" %>
          <h2>Experience Level</h2>
          <p>Whether you’re right out of school or looking for something more out of your career, the Management Training Program will put you in a position to succeed immediately. You’ll learn how to run a million-dollar business, maximize profits and motivate a team of professionals, while having fun along the way.</p>
        </div><!-- /.span3 -->
        <div class="span3">
          <%= image_tag "mgmt.jpg", :class => "img-circle" %>
          <h2>Management</h2>
          <p>This is where thousands of successful careers are launched – including our current CEO. Nearly all of our employees start in this program. You will learn our business from the inside out – taking care of customers, developing marketing plans and working with an energetic team of professionals. You’ll see just how much influence you can have on our future and on your own. As you progress through the program, you’ll see many more career options open to you.</p>
        </div><!-- /.span3 -->
      </div><!-- /.row -->


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="featurette">
      	<%= image_tag "advantage.jpg", :class => "featurette-image pull-right" %>
        <h2 class="featurette-heading">Take Advantage of the Opportunity… </h2>
        <p class="lead">Very seldom do we find the opportunity that allows us to climb the ladder of success by working hard and being rewarded accordingly for it. This is that OPPORTUNITY! Don’t miss the chance to achieve your goals and aspirations for the future. We will review all applications submitted, no matter the experience level you have. Are you ready? Are you driven? determined? Excited about attaining goals? How fast will you climb the ladder?</p>
        <%= link_to "Join our team now", apply_path , :class => "btn btn-large btn-primary btn_custom" %>
      </div>



      <!-- /END THE FEATURETTES -->

      <%= render "digitalPresence" %>


     <%= render "footer" %>

app/views/static_pages/home.html.erb
<!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag "slide-01.jpg"%>
          <div class="container">
            <div class="carousel-caption">
              <h1>Welcome to <%= @company.name %></h1>
              <p class="lead">The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will." - Vince Lombardi</p>
              <%= link_to "Apply Today!",	apply_path, :class => "btn btn-large btn-primary btn_custom  "  %>
            </div>
          </div>
        </div>
        <div class="item">
          <%= image_tag "slide-02.jpg" %>
          <div class="container">
            <div class="carousel-caption">
              <h1>Who We Are</h1>
              <p class="lead"><%= @company.name %> is a marketing firm that specializes in marketing programs for our clients’ products and services. The client base for <%= @company.name %> has expanded to leaders in Satellite Television and Consumer Electronics...</p>
              <%= link_to "Learn more",	aboutus_path, :class => "btn btn-large btn-primary btn_custom "  %>

            </div>
          </div>
        </div>
        <div class="item">
          <%= image_tag "slide-03.jpg" %>
          <div class="container">
            <div class="carousel-caption">
              <h1>Careers</h1>
              <p class="lead">We seek candidates with entrepreneurial spirit who are excited to start with our company at the entry level and grow into an upper level management position. Over the course of the last year we have expanded our portfolio and grown into new locations...</p>
              <%= link_to "Apply Today!",	apply_path, :class => "btn btn-large btn-primary btn_custom "  %>
            </div>
          </div>
        </div>
        <div class="item">
          <%= image_tag "slide-04.jpg" %>
          <div class="container">
            <div class="carousel-caption">
              <h1>CLIENT PORTFOLIO</h1>
              <p class="lead"><%= @company.name %> was created to acquire and retain customers in a personalized manner for all types of companies. Today, we lead the nation in outsourced marketing and innovative marketing campaigns...</p>
              <%= link_to "Services",	services_path, :class => "btn btn-large btn-primary btn_custom "  %>
              
            </div>
          </div>
        </div>


      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div><!-- /.carousel -->



    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="featurette">
        <h2 class="featurette-heading">Welcome to <%= @company.name %></h2>
        <h3><span class="muted">“A successful man is one who can lay a firm foundation with the bricks others have thrown at him. -David Brinkley ”</span></h3>
        <p class="lead"><%= @company.name %> lives by a company philosophy of loyalty to our people and results for our clients. Our success is built upon standards of only promoting from within, leading by example at all times, and working as hard for our clients as we would for ourselves. <%= @company.name %> strives to be the perfect combination of entrepreneurial spirit, superb client service, and successful business professionals.</p>
        <%= link_to "Click here to learn more", services_path %>
      </div>



      <!-- /END THE FEATURETTES -->

      <%= render "digitalPresence" %>

     <%= render "footer" %>

app/views/static_pages/new_applicant_email.html.erb
<%= render "digitalPresence" %>

<%= render "footer" %>

app/views/static_pages/questions.html.erb
<%= render "digitalPresence" %>

<%= render "footer" %>

app/views/static_pages/services.html.erb
<% provide(:title, 'Services') %>

<!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag "city.jpg" %>
          <div class="container">
            <div class="carousel-caption">
              <h1><%= @company.name %> Services</h1>
              <p class="lead">“In order to succeed, your desire for success should be greater than your fear of failure. ” ― Bill Cosby</p>
            </div>
          </div>
        </div>

      </div>
     
    </div><!-- /.carousel -->




      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="featurette">
        <h2 class="featurette-heading">What we do </h2>
        <%= image_tag "servicescol.png", :style => "float:right;" %>
        <p class="lead"><%= @company.name %> was created to acquire and retain customers in a personalized manner for all types of companies. Today, we lead the nation in outsourced marketing and innovative marketing campaigns.  Client acquisition is one of the fastest growing trends in marketing these days. We set the standard for bringing suppliers and customers together in an easy going unobtrusive way.</p>

        <p class="lead">We give the advertiser an opportunity to rise far above their competition with proven and measurable results. We take the campaigns to the next level and secure the consumer for the client directly.

        <ul>
        	<li>Professional Representatives</li>
        	<li>Teamwork</li>
        	<li>Leadership</li>
        	<li>Mentorship</li>
        	<li>Drive & Determination</li>
        	<li>Focus on the Consumer</li>
        	<li>Professional Campaigns</li>
        	<li>Reaching Our Goals</li>
        	<li>Success is at your fingertips</li>
        </ul>
        </p>
      </div>

      <div class="featurette">
        <h2 class="featurette-heading">HOW IT WORKS </h2>
        <p class="lead">

        Our clients have specific fields of expertise in satellite TV services and the entertainment, technology and home improvement industries. We feel we can complement their niche with a superior marketing and sales team to keep them busy doing what they do best. With hundreds of representatives nationally, our one-on-one approach allows us to get personal with our clients’ customers..</p>
        
      </div>

      <div class="featurette">
        <h2 class="featurette-heading">OUR APPROACH </h2>
        <p class="lead">Our in store approach within large retail venues allows us to target shoppers who may already be in a ‘spending’ mind frame already.  We are able to market the product or service more effectively because of this. Allowing the consumer to interact with the representatives helps to create an energy that attracts attention. The overwhelming response has been to the real world value and savings we are able to offer the consumer.</p>
        
      </div>

      <div class="featurette">
        <h2 class="featurette-heading">Why Our System Works… </h2>
        <p class="lead">The client has always been our top priority, as they are the reason for our tremendous success and growth opportunity. We are constantly evolving as we grow as a company and an organization across the country.</p>
        
      </div>

      <div class="featurette">
        <h2 class="featurette-heading">LOOKING FOR THE RIGHT CAREER OPPORTUNITY FOR YOU? </h2>
        <p class="lead">Our company seeks candidates with entrepreneurial spirit who are excited to start with our company at the entry level and grow into an upper level management position. Over the course of the last year we have expanded out client portfolio and grown into new divisions and locations. Our goal is for driven and self-motivated candidates to complete our training program and ultimately oversee new programs, markets, and locations on regional and national levels…</p>

        <%= link_to "Apply Today", apply_path,  class: "btn btn-large btn-primary btn_custom" %>
        
      </div>



      <!-- /END THE FEATURETTES -->

      <%= render "digitalPresence" %>


     <%= render "footer" %>